export const TEAM_LOGOS = {
  "ac milan": "https://images.fotmob.com/image_resources/logo/teamlogo/8564.png",
  "angers": "https://images.fotmob.com/image_resources/logo/teamlogo/8121.png",
  "arsenal": "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
  "aston villa": "https://images.fotmob.com/image_resources/logo/teamlogo/10252.png",
  "atalanta": "https://images.fotmob.com/image_resources/logo/teamlogo/8524.png",
  "athletic club": "https://images.fotmob.com/image_resources/logo/teamlogo/8315.png",
  "atletico madrid": "https://images.fotmob.com/image_resources/logo/teamlogo/9906.png",
  "augsburg": "https://images.fotmob.com/image_resources/logo/teamlogo/8406.png",
  "auxerre": "https://images.fotmob.com/image_resources/logo/teamlogo/8583.png",
  "barcelona": "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
  "bayer leverkusen": "https://images.fotmob.com/image_resources/logo/teamlogo/8178.png",
  "bayern": "https://images.fotmob.com/image_resources/logo/teamlogo/9823.png",
  "bologna": "https://images.fotmob.com/image_resources/logo/teamlogo/9857.png",
  "borussia dortmund": "https://images.fotmob.com/image_resources/logo/teamlogo/9789.png",
  "bournemouth": "https://images.fotmob.com/image_resources/logo/teamlogo/8678.png",
  "brentford": "https://images.fotmob.com/image_resources/logo/teamlogo/9937.png",
  "brest": "https://images.fotmob.com/image_resources/logo/teamlogo/8521.png",
  "brighton": "https://images.fotmob.com/image_resources/logo/teamlogo/10204.png",
  "burnley": "https://images.fotmob.com/image_resources/logo/teamlogo/8191.png",
  "cagliari": "https://images.fotmob.com/image_resources/logo/teamlogo/8529.png",
  "celta vigo": "https://images.fotmob.com/image_resources/logo/teamlogo/9910.png",
  "chelsea": "https://images.fotmob.com/image_resources/logo/teamlogo/8455.png",
  "como": "https://images.fotmob.com/image_resources/logo/teamlogo/10171.png",
  "cremonese": "https://images.fotmob.com/image_resources/logo/teamlogo/7801.png",
  "crystal palace": "https://images.fotmob.com/image_resources/logo/teamlogo/9826.png",
  "deportivo alaves": "https://images.fotmob.com/image_resources/logo/teamlogo/9866.png",
  "eintracht frankfurt": "https://images.fotmob.com/image_resources/logo/teamlogo/9810.png",
  "elche": "https://images.fotmob.com/image_resources/logo/teamlogo/10268.png",
  "espanyol": "https://images.fotmob.com/image_resources/logo/teamlogo/8558.png",
  "everton": "https://images.fotmob.com/image_resources/logo/teamlogo/8668.png",
  "fc heidenheim": "https://images.fotmob.com/image_resources/logo/teamlogo/94937.png",
  "fc koln": "https://images.fotmob.com/image_resources/logo/teamlogo/8722.png",
  "fiorentina": "https://images.fotmob.com/image_resources/logo/teamlogo/8535.png",
  "freiburg": "https://images.fotmob.com/image_resources/logo/teamlogo/8358.png",
  "fulham": "https://images.fotmob.com/image_resources/logo/teamlogo/9879.png",
  "genoa": "https://images.fotmob.com/image_resources/logo/teamlogo/10233.png",
  "getafe": "https://images.fotmob.com/image_resources/logo/teamlogo/8305.png",
  "girona": "https://images.fotmob.com/image_resources/logo/teamlogo/7732.png",
  "hamburger sv": "https://images.fotmob.com/image_resources/logo/teamlogo/9790.png",
  "hoffenheim": "https://images.fotmob.com/image_resources/logo/teamlogo/8226.png",
  "inter": "https://images.fotmob.com/image_resources/logo/teamlogo/8636.png",
  "juventus": "https://images.fotmob.com/image_resources/logo/teamlogo/9885.png",
  "lazio": "https://images.fotmob.com/image_resources/logo/teamlogo/8543.png",
  "le havre": "https://images.fotmob.com/image_resources/logo/teamlogo/9746.png",
  "lecce": "https://images.fotmob.com/image_resources/logo/teamlogo/9888.png",
  "leeds": "https://images.fotmob.com/image_resources/logo/teamlogo/8463.png",
  "lens": "https://images.fotmob.com/image_resources/logo/teamlogo/8588.png",
  "levante": "https://images.fotmob.com/image_resources/logo/teamlogo/8581.png",
  "lille": "https://images.fotmob.com/image_resources/logo/teamlogo/8639.png",
  "liverpool": "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
  "lorient": "https://images.fotmob.com/image_resources/logo/teamlogo/8689.png",
  "lyon": "https://images.fotmob.com/image_resources/logo/teamlogo/9748.png",
  "mainz 05": "https://images.fotmob.com/image_resources/logo/teamlogo/9905.png",
  "mallorca": "https://images.fotmob.com/image_resources/logo/teamlogo/8661.png",
  "man city": "https://images.fotmob.com/image_resources/logo/teamlogo/8456.png",
  "marseille": "https://images.fotmob.com/image_resources/logo/teamlogo/8592.png",
  "metz": "https://images.fotmob.com/image_resources/logo/teamlogo/8550.png",
  "monaco": "https://images.fotmob.com/image_resources/logo/teamlogo/9829.png",
  "nantes": "https://images.fotmob.com/image_resources/logo/teamlogo/9830.png",
  "napoli": "https://images.fotmob.com/image_resources/logo/teamlogo/9875.png",
  "newcastle": "https://images.fotmob.com/image_resources/logo/teamlogo/10261.png",
  "nice": "https://images.fotmob.com/image_resources/logo/teamlogo/9831.png",
  "nottingham forest": "https://images.fotmob.com/image_resources/logo/teamlogo/10203.png",
  "osasuna": "https://images.fotmob.com/image_resources/logo/teamlogo/8371.png",
  "paris fc": "https://images.fotmob.com/image_resources/logo/teamlogo/6379.png",
  "paris saint germain": "https://images.fotmob.com/image_resources/logo/teamlogo/9847.png",
  "parma calcio 1913": "https://images.fotmob.com/image_resources/logo/teamlogo/1184312.png",
  "pisa": "https://images.fotmob.com/image_resources/logo/teamlogo/6479.png",
  "rayo vallecano": "https://images.fotmob.com/image_resources/logo/teamlogo/8370.png",
  "rb leipzig": "https://images.fotmob.com/image_resources/logo/teamlogo/178475.png",
  "real betis": "https://images.fotmob.com/image_resources/logo/teamlogo/8603.png",
  "real madrid": "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
  "real oviedo": "https://images.fotmob.com/image_resources/logo/teamlogo/8670.png",
  "real sociedad": "https://images.fotmob.com/image_resources/logo/teamlogo/8560.png",
  "rennes": "https://images.fotmob.com/image_resources/logo/teamlogo/9851.png",
  "roma": "https://images.fotmob.com/image_resources/logo/teamlogo/8686.png",
  "sassuolo": "https://images.fotmob.com/image_resources/logo/teamlogo/7943.png",
  "sevilla": "https://images.fotmob.com/image_resources/logo/teamlogo/8302.png",
  "spurs": "https://images.fotmob.com/image_resources/logo/teamlogo/8586.png",
  "st. pauli": "https://images.fotmob.com/image_resources/logo/teamlogo/8152.png",
  "strasbourg": "https://images.fotmob.com/image_resources/logo/teamlogo/9848.png",
  "sunderland": "https://images.fotmob.com/image_resources/logo/teamlogo/8472.png",
  "torino": "https://images.fotmob.com/image_resources/logo/teamlogo/9804.png",
  "tottenham": "https://images.fotmob.com/image_resources/logo/teamlogo/8586.png",
  "toulouse": "https://images.fotmob.com/image_resources/logo/teamlogo/9941.png",
  "udinese": "https://images.fotmob.com/image_resources/logo/teamlogo/8600.png",
  "union berlin": "https://images.fotmob.com/image_resources/logo/teamlogo/8149.png",
  "valencia": "https://images.fotmob.com/image_resources/logo/teamlogo/10267.png",
  "verona": "https://images.fotmob.com/image_resources/logo/teamlogo/9876.png",
  "vfb stuttgart": "https://images.fotmob.com/image_resources/logo/teamlogo/10269.png",
  "villarreal": "https://images.fotmob.com/image_resources/logo/teamlogo/10205.png",
  "werder bremen": "https://images.fotmob.com/image_resources/logo/teamlogo/8697.png",
  "west ham": "https://images.fotmob.com/image_resources/logo/teamlogo/8654.png",
  "wolfsburg": "https://images.fotmob.com/image_resources/logo/teamlogo/8721.png",
  "wolves": "https://images.fotmob.com/image_resources/logo/teamlogo/8602.png"
};

export function getTeamLogo(teamName) {
  const normalized = Object.keys(TEAM_LOGOS).find(key => 
    teamName.toLowerCase().includes(key.toLowerCase())
  );
  
  if (normalized) {
    return TEAM_LOGOS[normalized];
  }

  // Beautiful monogram fallback securely using ui-avatars.
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(teamName)}&background=111827&color=fff&rounded=true&bold=true&format=svg`;
}
